version: "3"
# this file uses latest image built locally, tagged with below image name 
services:
  jekyll:
    image: my-jekyll-site:latest
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
